global:
  appVersion: "v1"

frontend:
  replicaCount: 1
  image:
    repository: sushi-frontend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    # Wenn leer, wird automatisch auf den Backend-Service dieses Releases gesetzt.
    BACKEND_URL: ""
    BG_COLOR: "green"
    APP_VERSION: "v1"
  resources: {}

backend:
  replicaCount: 1
  image:
    repository: sushi-backend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    APP_VERSION: "v1"
  resources: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: sushi.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
