apiVersion: v1
kind: Service
metadata:
  name: {{ include "sushi-bar.fullname" . }}-frontend
  labels:
    {{- include "sushi-bar.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80

