apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sushi-bar.fullname" . }}-frontend-config
  labels:
    {{- include "sushi-bar.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ default (printf "http://%s-backend:80" (include "sushi-bar.fullname" .)) .Values.frontend.env.BACKEND_URL | quote }}
  BG_COLOR: {{ .Values.frontend.env.BG_COLOR | quote }}
  APP_VERSION: {{ .Values.frontend.env.APP_VERSION | quote }}
